import type { Colorway } from '$lib/types';

const colorways: Colorway[] = [
  {
    source: {
      name: 'lovecrafts.com',
      href: 'https://www.lovecrafts.com/en-gb/p/paintbox-yarns-simply-dk',
      accessed: '2023-07-13',
    },
    colors: [
      { name: 'Elephant Grey', hex: '#c8c6c5' },
      { name: 'Rosy Pink', hex: '#f1c8bf' },
      { name: 'Summer Sky Blue', hex: '#9daecd' },
      { name: 'Rich Teal', hex: '#1d3f5b' },
      { name: 'Pear Green', hex: '#9b9956' },
      { name: 'Glorious Gold', hex: '#ce8a37' },
      { name: 'Pine Green', hex: '#879890' },
      { name: 'Deep Sea Blue', hex: '#313b49' },
      { name: 'Vintage Heather', hex: '#99737a' },
      { name: 'Macaron Green', hex: '#e3f1db' },
      { name: 'Navy Night', hex: '#242d3c' },
      { name: 'Jewel', hex: '#347186' },
      { name: 'Jam', hex: '#35193c' },
      { name: 'Cerulean Blue', hex: '#7d8aa7' },
      { name: 'Taupe', hex: '#bbaea0' },
      { name: 'Paper White', hex: '#e8e8ea' },
      { name: 'Pure Black', hex: '#1B191a' },
      { name: 'Champagne White', hex: '#f1e9df' },
      { name: 'Misty Grey', hex: '#dcdadf' },
      { name: 'Stormy Grey', hex: '#cccdd0' },
      { name: 'Slate Grey', hex: '#7f7a7c' },
      { name: 'Granite Grey', hex: '#3d383a' },
      { name: 'Vanilla Cream', hex: '#dfcec4' },
      { name: 'Light Caramel', hex: '#d8b488' },
      { name: 'Soft Fudge', hex: '#ad8160' },
      { name: 'Coffee Bean', hex: '#4f3628' },
      { name: 'Rose Red', hex: '#c52b2f' },
      { name: 'Pillar Red', hex: '#781723' },
      { name: 'Red Wine', hex: '#621221' },
      { name: 'Blood Orange', hex: '#d76d32' },
      { name: 'Banana Cream', hex: '#ebddaf' },
      { name: 'Daffodil Yellow', hex: '#f6d379' },
      { name: 'Buttercup Yellow', hex: '#f4c64f' },
      { name: 'Mustard Yellow', hex: '#e6ad41' },
      { name: 'Pistachio Green', hex: '#bcbeaa' },
      { name: 'Spearmint Green', hex: '#93c292' },
      { name: 'Slate Green', hex: '#658277' },
      { name: 'Racing Green', hex: '#243223' },
      { name: 'Lime Green', hex: '#9fa245' },
      { name: 'Grass Green', hex: '#387946' },
      { name: 'Seafoam Blue', hex: '#c6d8de' },
      { name: 'Washed Teal', hex: '#afced2' },
      { name: 'Marine Blue', hex: '#57b8d0' },
      { name: 'Kingfisher Blue', hex: '#3575b7' },
      { name: 'Duck Egg Blue', hex: '#c5cfe1' },
      { name: 'Dolphin Blue', hex: '#6884b4' },
      { name: 'Midnight Blue', hex: '#1f2047' },
      { name: 'Sailor Blue', hex: '#263683' },
      { name: 'Royal Blue', hex: '#222762' },
      { name: 'Dusty Rose', hex: '#d2c5da' },
      { name: 'Tea Rose', hex: '#cea4d1' },
      { name: 'Raspberry Pink', hex: '#882859' },
      { name: 'Pale Lilac', hex: '#bdb7d8' },
      { name: 'Dusty Lilac', hex: '#998cb4' },
      { name: 'Pansy Purple', hex: '#5b3a7f' },
      { name: 'Dark Aubergine', hex: '#2a1d3e' },
      { name: 'Candyfloss Pink', hex: '#e9cfd9' },
      { name: 'Bubblegum Pink', hex: '#e796ae' },
      { name: 'Lipstick Pink', hex: '#c6324e' },
      { name: 'Ballet Pink', hex: '#f9e3e1' },
      { name: 'Blush Pink', hex: '#e1a7a4' },
      { name: 'Peach Orange', hex: '#f0b69d' },
      { name: 'Vintage Pink', hex: '#e39e87' },
    ],
  },
];
export default colorways;
