// Generates the D1 migration for Better Auth's tables from the app's own auth options.
//
//   node scripts/generate-auth-migration.ts            # print the SQL still needed
//   node scripts/generate-auth-migration.ts <name>     # write it to migrations/NNNN_<name>.sql
//
// The Better Auth CLI can't reach D1, so this applies the existing migrations to an
// in-memory SQLite database and asks Better Auth what's missing. Rerun it after
// adding or changing a plugin.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { register } from 'node:module';
import { DatabaseSync } from 'node:sqlite';
import { getMigrations } from 'better-auth/db/migration';

// The app's own modules import each other without file extensions (resolved by
// Vite). Node needs them, so retry extensionless relative imports with .ts.
register(
  'data:text/javascript,' +
    encodeURIComponent(`
      export async function resolve(specifier, context, next) {
        try {
          return await next(specifier, context);
        } catch (error) {
          if (specifier.startsWith('.') && !/\\.[cm]?[jt]s$/.test(specifier))
            return next(specifier + '.ts', context);
          throw error;
        }
      }`),
);
const { buildAuthOptions } = await import('../src/lib/server/auth/options.ts');

const MIGRATIONS_DIR = 'migrations';

const existing = readdirSync(MIGRATIONS_DIR)
  .filter((file) => /^\d{4}_.+\.sql$/.test(file))
  .sort();

const db = new DatabaseSync(':memory:');
for (const file of existing) {
  db.exec(readFileSync(`${MIGRATIONS_DIR}/${file}`, 'utf8'));
}

const options = buildAuthOptions({
  database: db,
  secret: 'migration-generator-secret-not-used-at-runtime',
  allowedHosts: ['localhost'],
  protocol: 'http',
  sendSignInCode: async () => {},
  runInBackground: () => {},
  validateSchema: false,
  // Optional providers on, so their schema needs are included
  google: { clientId: 'x', clientSecret: 'x' },
});

const { compileMigrations } = await getMigrations(options);
// Nothing to do compiles to a bare ";"
const sql = (await compileMigrations()).replace(/^[\s;]+$/, '').trim();

if (!sql) {
  console.log('The migrations already match the auth options.');
  process.exit(0);
}

const name = process.argv[2];
if (!name) {
  console.log(sql);
  console.error('\nPass a name to write this as a migration.');
  process.exit(1);
}

const next = String(existing.length + 1).padStart(4, '0');
const path = `${MIGRATIONS_DIR}/${next}_${name}.sql`;
writeFileSync(
  path,
  `-- Generated by scripts/generate-auth-migration.ts from src/lib/server/auth/options.ts\n\n${sql}\n`,
);
console.log(`Wrote ${path}`);
