import type { Colorway } from '$lib/types';

const colorways: Colorway[] = [
  {
    source: {
      name: 'premieryarns.com',
      href: 'https://www.premieryarns.com/products/pbasix',
      accessed: '2023-10-16',
    },
    colors: [
      { name: 'Cherry Red', hex: '#7c1717' },
      { name: 'Dijon Mustard', hex: '#ca8f32' },
      { name: 'Sweet Potato', hex: '#bd4935' },
      { name: 'Lime', hex: '#888a35' },
      { name: 'Spruce', hex: '#515a3b' },
      { name: 'Bright Blue', hex: '#3b83b1' },
      { name: 'Raspberry', hex: '#a43754' },
      { name: 'Wisteria', hex: '#b9aeb5' },
      { name: 'Foliage Marl', hex: '#647665' },
      { name: 'Caribbean Marl', hex: '#5ea6b6' },
      { name: 'Monochrome Marl', hex: '#8d8e89' },
      { name: 'Rose Quartz Marl', hex: '#847a78' },
      { name: 'Aran Tweed', hex: '#b6b0a2' },
      { name: 'Gray Tweed', hex: '#797e82' },
      { name: 'Cream Tweed', hex: '#ccc6b3' },
      { name: 'White', hex: '#ddddd5' },
      { name: 'Light Gray', hex: '#9d9d98' },
      { name: 'Gray', hex: '#676058' },
      { name: 'Black', hex: '#1c1a15' },
      { name: 'Lemon', hex: '#e5c96d' },
      { name: 'Coral', hex: '#eab290' },
      { name: 'Ballet', hex: '#e6c8c2' },
      { name: 'Pink', hex: '#e7a9b3' },
      { name: 'Fuchsia', hex: '#ad2f4b' },
      { name: 'Taffy', hex: '#cb7a77' },
      { name: 'Rose', hex: '#a35259' },
      { name: 'Red', hex: '#801913' },
      { name: 'Garnet', hex: '#591310' },
      { name: 'Burgundy', hex: '#4f1f1d' },
      { name: 'Crepe', hex: '#d8cdbf' },
      { name: 'Blush', hex: '#d0b3b3' },
      { name: 'Light Mauve', hex: '#c29c99' },
      { name: 'Lilac', hex: '#decddf' },
      { name: 'Purple', hex: '#603b59' },
      { name: 'Eggplant', hex: '#371b29' },
      { name: 'Royal Blue', hex: '#1b4182' },
      { name: 'Light Blue', hex: '#9eb7d4' },
      { name: 'Slate', hex: '#5b6f83' },
      { name: 'Azure', hex: '#2b4673' },
      { name: 'Denim', hex: '#313a4b' },
      { name: 'Seaglass', hex: '#84cdbd' },
      { name: 'Aqua', hex: '#65c0c9' },
      { name: 'Turquoise', hex: '#408eb2' },
      { name: 'Peacock', hex: '#255470' },
      { name: 'Cream', hex: '#e1ddc9' },
      { name: 'Hazel', hex: '#c1b197' },
      { name: 'Taupe', hex: '#a68e7a' },
      { name: 'Pecan', hex: '#674d3e' },
      { name: 'Leaf', hex: '#4e522b' },
      { name: 'Juniper', hex: '#293126' },
      { name: 'Mustard', hex: '#c68e37' },
      { name: 'Forest Green', hex: '#3f3b1a' },
      { name: 'Navy', hex: '#1f1d2d' },
      { name: 'Aran', hex: '#dcd5c2' },
      { name: 'Nutmeg', hex: '#8f7260' },
      { name: 'Pumpkin', hex: '#7f3628' },
      { name: 'Linen', hex: '#e0d5c1' },
      { name: 'Teal', hex: '#183a41' },
      { name: 'Ember', hex: '#701f16' },
      { name: 'Charcoal', hex: '#1f1d19' },
      { name: 'Chocolate', hex: '#4c3320' },
      { name: 'Goldenrod', hex: '#be8133' },
      { name: 'Peach', hex: '#dba687' },
      { name: 'Steel', hex: '#636368' },
      { name: 'Thistle', hex: '#89758e' },
      { name: 'Goldfish', hex: '#c74722' },
      { name: 'Butterscotch', hex: '#744e34' },
      { name: 'Pine', hex: '#193f31' },
      { name: 'Orange', hex: '#963c25' },
      { name: 'Sage', hex: '#707662' },
      { name: 'Spring Green', hex: '#4e7f30' },
      { name: 'Fern', hex: '#526131' },
      { name: 'Maize', hex: '#c89f61' },
      { name: 'Buff', hex: '#ba9d79' },
      { name: 'Violet', hex: '#594673' },
      { name: 'Salmon', hex: '#ac413f' },
      { name: 'Storm', hex: '#517686' },
      { name: 'Pale Orchid', hex: '#b17c92' },
      { name: 'Chestnut', hex: '#965c4a' },
      { name: 'Toffee', hex: '#725347' },
      { name: 'Warm Beige', hex: '#caa382' },
      { name: 'Apricot', hex: '#e0ccb9' },
      { name: 'Cocoa', hex: '#7d5440' },
      { name: 'Mahogany', hex: '#3e261e' },
    ],
  },
];
export default colorways;
